package staticsynchronization;

class Bracket {
    synchronized static public void generate(String threadCode) {
        for (int i = 0; i < 10; i++) {
            if(i<5) {
                System.out.print("[");
            } else {
                System.out.print("]");
            }
        }
        System.out.println("Generated by thread: " + threadCode);
    }
}

public class StaticSynchronization {

    public static void main(String[] args) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 5; i++) {
                    Bracket.generate("Thread1");
                }
            }
        }).start();
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 5; i++) {
                    Bracket.generate("Thread2");
                }
            }
        }).start();
    }
}
